#!/bin/bash
## local copy of echo to the requestor.
send()
{
    echo "$@" >&${out}
}

## Initialize Command Line. Redirect stdout, then close stdout and stderr so output does not get garbled by output of commands.
exec 2>&- {out}>&1- 1>/dev/null 2>&1
PATH=/bin:/sbin
CMD="$(cut -d " " -f1 <<< "$2")"
OBJ="$(cut -d " " -f2 <<< "$2")"
PASS="$(cut -d " " -f3- <<< "$2")"
SSH_CLIENT="${SSH_CLIENT%% *}"

keyctl link @us @s
[ ! -d ~/keys ] && mkdir ~/keys
[ ! -f ~/.hushlogin ] && touch ~/.hushlogin 

## Parse Commands
case ${CMD^^} in
    GET)
        # Find the key and get the passphrase.
	    key="$(keyctl request user ${OBJ})"
       	[[ ! -z "${key}" ]] && passphrase="$(keyctl pipe ${key})"
    	if [[ -z "${key}" ]] || ! openssl aes-256-cbc -d -salt -pbkdf2 -in ~/keys/${OBJ}.key -out /dev/null -k "${passphrase}"; then
            if [[ -z "${key}" ]]; then
               	logger -p user.error "Sanboot for ${USER} (${SSH_CLIENT}): Did not Find Passphrase ${OBJ}."
            else
                #The requstor has probably updated the key since it was loaded, revoke it.
                logger -p user.error "Sanboot for ${USER} (${SSH_CLIENT}): Passphrase ${OBJ} does not match stored key file. Revoking."
    		    keyctl revoke ${key}
            fi
            # Kill the ssh client so that the requestor will get an error.
            kill -SIGKILL $PPID
            exit 1
        fi
        logger "Sanboot for ${USER} (${SSH_CLIENT}): Found Passphrase ${OBJ}."
    	send "${passphrase}";;
    PUT)
    	if openssl aes-256-cbc -d -salt -pbkdf2 -in ~/keys/${OBJ}.key -out /dev/null -k "${PASS}"; then
    		logger "Sanboot for ${USER} (${SSH_CLIENT}): Recevied Passphrase ${OBJ} Equal to Stored Passphrase, Ignoring."
    		send "SAME"
    	else
    		if ! head -c1024 /dev/urandom | openssl aes-256-cbc -e -pbkdf2 -salt -in - -out ~/keys/${OBJ}.key -k "${PASS}"; then
        		logger -p user.error "Sanboot for ${USER} ($SSH_CLIENT): PUT of Passphrase ${OBJ} failed."
    			send "NOK"
    		else
    			logger "Sanboot for ${USER} (${SSH_CLIENT}): PUT of Passphrase ${OBJ} succeeded."
    		    send "OK"
    		fi
    	fi;;
    DEL)
        if rm -f ~/keys/${OBJ}.key; then
            send "OK"
        else
            send "NOK"
        fi;;
	**)
		logger -p user.error "Sanboot for ${USER}: Received Incorrect Command from ${SSH_CLIENT}.";;
esac
